Warning message
OpenLiberty/guide-microprofile-rest-client pull request #138
Opened 2020-10-13 15:26 UTC by tt-le

Added warning message thrown by test case and explaining that it is expected.

2020-10-14 13:56 UTC, AustinSeto approved these changes
LGTM

2020-10-20 21:36 UTC, gkwan-ibm commented on README.adoc
> +The warning message is expected and result from a request to a bad or an unknown host name.
@tt-le better mention the test `testUnknownHost()` causes the warning/error

2020-10-20 21:37 UTC, gkwan-ibm requested changes
@tt-le better mention the test `testUnknownHost()` causes the warning/error

2020-11-26 19:50 UTC, griffinhadfield commented
Verified in lgdev. Looks good to me.

2020-11-26 20:05 UTC, griffinhadfield approved these changes

2020-11-26 22:44 UTC, gkwan-ibm approved these changes

2020-11-26 22:52 UTC, merged